---
dist: trusty
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.5.3
stages:
  - static
  - spec
  - acceptance
  -
    if: tag =~ ^v\d
    name: deploy
matrix:
  fast_finish: true
  include:
    -
      env: CHECK="check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop syntax lint metadata_lint"
      stage: static
    -
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
      rvm: 2.4.5
      stage: spec
    -
      env: PUPPET_GEM_VERSION="~> 6.0" CHECK=parallel_spec
      rvm: 2.5.3
      stage: spec
    -
      sudo: required
      services: docker
      env:
        - PUPPET_INSTALL_TYPE=agent
        - BEAKER_IS_PE=no
        - BEAKER_PUPPET_COLLECTION=puppet5
        - BEAKER_debug=true
        - BEAKER_setfile=centos6-64{hypervisor=docker}
      rvm: default
      bundler_args:
      script: bundle exec rspec spec/acceptance/*_spec.rb
    -
      sudo: required
      services: docker
      env:
        - PUPPET_INSTALL_TYPE=agent
        - BEAKER_IS_PE=no
        - BEAKER_PUPPET_COLLECTION=puppet6
        - BEAKER_debug=true
        - BEAKER_setfile=centos6-64{hypervisor=docker}
      rvm: default
      bundler_args:
      script: bundle exec rspec spec/acceptance/*_spec.rb
    -
      sudo: required
      services: docker
      env:
        - PUPPET_INSTALL_TYPE=agent
        - BEAKER_IS_PE=no
        - BEAKER_PUPPET_COLLECTION=puppet5
        - BEAKER_debug=true
        - BEAKER_setfile=centos7-64{hypervisor=docker}
      rvm: default
      bundler_args:
      script: bundle exec rspec spec/acceptance/*_spec.rb
    -
      sudo: required
      services: docker
      env:
        - PUPPET_INSTALL_TYPE=agent
        - BEAKER_IS_PE=no
        - BEAKER_PUPPET_COLLECTION=puppet6
        - BEAKER_debug=true
        - BEAKER_setfile=centos7-64{hypervisor=docker}
      rvm: default
      bundler_args:
      script: bundle exec rspec spec/acceptance/*_spec.rb
    -
      env: DEPLOY_TO_FORGE=yes
      stage: deploy
branches:
  only:
    - master
    - /^v\d/
notifications:
  email: false
deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: ""
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
