---
os: linux
dist: xenial
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - "# Update system gems if requested. This is useful to temporarily workaround troubles in the test runner"
  - "# See https://github.com/puppetlabs/pdk-templates/commit/705154d5c437796b821691b707156e1b056d244f for an example of how this was used"
  - "# Ignore exit code of SIGPIPE'd yes to not fail with shell's pipefail set"
  - '[ -z "$RUBYGEMS_VERSION" ] || (yes || true) | gem update --system $RUBYGEMS_VERSION'
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.5.7
stages:
  - static
  - spec
  - acceptance
  -
    if: tag =~ ^v\d
    name: deploy
jobs:
  fast_finish: true
  include:
    -
      env: CHECK="check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop syntax lint metadata_lint"
      stage: static
    -
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
      rvm: 2.4.5
      stage: spec
    -
      env: PUPPET_GEM_VERSION="~> 6.0" CHECK=parallel_spec
      rvm: 2.5.7
      stage: spec
    -
      sudo: required
      services: docker
      env:
        - PUPPET_INSTALL_TYPE=agent
        - BEAKER_IS_PE=no
        - BEAKER_PUPPET_COLLECTION=puppet5
        - BEAKER_debug=true
        - BEAKER_setfile=centos6-64{hypervisor=docker}
      rvm: default
      bundler_args:
      script: bundle exec rspec spec/acceptance/init_spec.rb
    -
      sudo: required
      services: docker
      env:
        - PUPPET_INSTALL_TYPE=agent
        - BEAKER_IS_PE=no
        - BEAKER_PUPPET_COLLECTION=puppet6
        - BEAKER_debug=true
        - BEAKER_setfile=centos6-64{hypervisor=docker}
      rvm: default
      bundler_args:
      script: bundle exec rspec spec/acceptance/init_spec.rb
    -
      sudo: required
      services: docker
      env:
        - PUPPET_INSTALL_TYPE=agent
        - BEAKER_IS_PE=no
        - BEAKER_PUPPET_COLLECTION=puppet5
        - BEAKER_debug=true
        - BEAKER_setfile=centos7-64{hypervisor=docker}
      rvm: default
      bundler_args:
      script: bundle exec rspec spec/acceptance/init_spec.rb
    -
      sudo: required
      services: docker
      env:
        - PUPPET_INSTALL_TYPE=agent
        - BEAKER_IS_PE=no
        - BEAKER_PUPPET_COLLECTION=puppet6
        - BEAKER_debug=true
        - BEAKER_setfile=centos7-64{hypervisor=docker}
      rvm: default
      bundler_args:
      script: bundle exec rspec spec/acceptance/init_spec.rb
    -
      env: DEPLOY_TO_FORGE=yes
      stage: deploy
branches:
  only:
    - master
    - /^development\/.*/
    - /^v\d/
notifications:
  email: false
deploy:
  provider: puppetforge
  user: jmciver
  password:
    secure: "NZNWcr9fEwziBYeKd2gcJficDrpT5xgayKNFsRvA10CjUSC2enDT5Mzh7n5rmoxYKk1ep44gki7I0LwcPwXaOB/yVZEmGkAv+dkXra28ppo2OUCDGW517PangAhoLa3Al6ldTNByD4UQRbw9YhBVaFA7ADJjt2VptJyk2SSYSK/lbdz1l1qcv+7/71bDwtlwz7GxxUJpL/CE5FxqlhtsotR9mOBAnlYPSuym7xyDvYZU/XdGyRQDpBHEBFOHr4uP7hqOXhlEkCSmnJD/vxCWVhtdApBm2uyODt4soPopY7XtDvt5nj2lpk6VK4q5tX9Q3XxDTTKz/C6xwTiU9dUG5TXT3ihtaganGR/FExdaOE9ETnvz05nkRehGwnCNoDZg+Uz8CLJ3xNuFdWen/n9PLUnMEq1hcTJJnUBaj0hf7+t+qZMUGBkfPnYA87FPpJgmRG5n0P2Si+kfHrLYEtMNcyi1Azo9cFZy4NfFgPy7muMFnXwGyZCjsHYXIKEfMcu6ZqsZdzx+FoJJAT4e7QofmvPAspxv1ix22ruwZv2fW/tD0Bs0nF7Fjv4o/wAOoaXKsE0PDTGQUfKD9wJJWWNSDKNcKSwD1gk1wrTe4Uw+VseX+34uqU2mNMoS/pyP7ahnJyyof9XgXNnvVnmrBQSgZ36G8Mfb7ZoyPu7Q6UgTu/Y="
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
